version: '3.7'
services:
  web:
    container_name: circleci-web
    restart: always
    build: . 
    volumes:
      - .:/usr/app/
      - node_modules:/usr/app/node_modules
    ports:
      - "8080:3000"
    depends_on:
      - mongo
    links: 
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    environment:
      MONGODB_USER: "user"
      MONGODB_DATABASE: "circleCI"
      MONGODB_PASS: "userpass"
volumes:
 mongodb:
 node_modules:
