version: 2
jobs:
  build:
    working_directory: /dockerapp1
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
            cp .env.examble .env
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: |
            cp .env.examble .env
            docker-compose up -d --build
            sleep 5
            ls -a
            docker exec -it circleci_web npm run test
      - store_artifacts:
          path: test-reports/
          destination: circle_test
      # - deploy:
      #     name: Push application Docker image
      #     command: |
      #       docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
      #       docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp1:$CIRCLE_SHA1
      #       docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp1:latest
      #       docker push $DOCKER_HUB_USER_ID/dockerapp1:$CIRCLE_SHA1
      #       docker push $DOCKER_HUB_USER_ID/dockerapp1:latest